angularjs/SportsStore.WebUI/Controllers/CartController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
	public class CartController : Controller
	{
		//note 7. добавим readonly, обезопасив себя он подмены репозитория после внедрения в конструктор
		private readonly IProductRepository repository;
		private readonly IOrderProcessor orderProcessor;

		public CartController(IProductRepository repo, IOrderProcessor proc)
		{
			//note 8. добавим ограждающее условие, что бы быть уверенным -- внедрение прошло успешно
			//больше информации см. http://smarly.net/dependency-injection-in-net/di-catalog/di-patterns/constructor-injection#text-22427

			if (repo == null)
				throw new ArgumentNullException("repo");

			if (proc == null)
				throw new ArgumentNullException("proc");

			repository = repo;
			orderProcessor = proc;
		}

		public ViewResult Index(Cart cart, string returnUrl)
		{
			return View(new CartIndexViewModel
			{
				Cart = cart,
				ReturnUrl = returnUrl
			});
		}

		public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
		{
			Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);
			if (product != null)
			{
				cart.AddItem(product, 1);
			}
			return RedirectToAction("Index", new { returnUrl });
		}

		public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
		{
			Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);
			if (product != null)
			{
				cart.RemoveLine(product);
			}
			return RedirectToAction("Index", new { returnUrl });
		}

		public PartialViewResult Summary(Cart cart)
		{
			return PartialView(cart);
		}
		public ViewResult Checkout()
		{
			return View(new ShippingDetails());
		}

		[HttpPost]
		public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
		{
			if (!cart.Lines.Any())
			{
				ModelState.AddModelError("", "Sorry, your cart is empty!");
			}
			if (ModelState.IsValid)
			{
				orderProcessor.ProcessOrder(cart, shippingDetails);
				cart.Clear();
				return View("Completed");
			}
			else
			{
				return View(shippingDetails);
			}
		}
	}
}

angularjs/SportsStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;

namespace SportsStore.WebUI.Controllers
{
	public class NavController : Controller
	{
		//note 4. добавим readonly, обезопасив себя он подмены репозитория после внедрения в конструктор
		private readonly IProductRepository repository;

		public NavController(IProductRepository repo)
		{
			//note 5. добавим ограждающее условие, что бы быть уверенным -- внедрение прошло успешно
			//больше информации см. http://smarly.net/dependency-injection-in-net/di-catalog/di-patterns/constructor-injection#text-22427

			if (repo == null)
				throw new ArgumentNullException("repo");

			repository = repo;
		}

		public PartialViewResult Menu(string category = null)
		{
			//note 6. Добавлен ToList() для получения списка продуктов до передачи данных в представление
			//Отложенные методы расширения LINQ http://smarly.net/pro-asp-net-mvc-4/introducing-asp-net-mvc-4/essential-language-features/performing-language-integrated-queries#text-14929

			IEnumerable<string> categories = repository.Products
				.Select(x => x.Category)
				.Distinct()
				.OrderBy(x => x)
				.ToList();

			ViewBag.SelectedCategory = category;

			return PartialView(categories);
		}
	}
}

angularjs/SportsStore.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<link href="~/Content/Admin.css" rel="stylesheet" type="text/css" />
	
	@Scripts.Render("~/bundles/jquery")
	<script src="~/Scripts/jquery.validate.min.js"></script>
	<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
	<title></title>
</head>
<body>
	<div>
		@if (TempData["message"] != null)
		{
			<div class="Message">@TempData["message"]</div>
		}
		@RenderBody()
	</div>
</body>
</html>

angularjs/SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	<link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
</head>
<body>
	<div id="header">
		@{Html.RenderAction("Summary", "Cart");}
		<div class="title">SPORTS STORE</div>
	</div>
	<div id="categories">
		@{ Html.RenderAction("Menu", "Nav"); }
	</div>
	<div id="content">
		@RenderBody()
	</div>
</body>
</html>